name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js 🛠
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean previous install artifacts
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies with forced overrides
        run: |
          npm install --legacy-peer-deps

      - name: Verify ajv resolution
        run: |
          npm ls ajv
          npm ls ajv-keywords

      - name: Build project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
