name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js 🛠
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean previous install
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Manually install critical dependencies
        run: |
          npm install react-scripts@5.0.1 ajv@6.12.6 ajv-keywords@3.5.2 ajv-formats@2.1.1 --save
          npm install --legacy-peer-deps --force

      - name: Verify react-scripts presence
        run: |
          ls node_modules/react-scripts || echo "react-scripts not found"

      - name: Build project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
